[global]
error_log = /proc/self/fd/2

; https://github.com/docker-library/php/pull/725#issuecomment-443540114
log_limit = 8192

[www]
; php-fpm closes STDOUT on startup, so sending logs to /proc/self/fd/1 does not work.
; https://bugs.php.net/bug.php?id=73886
access.log = /proc/self/fd/2
access.format='{"severity": "%s", "message": "%R - %u %m %{REQUEST_URI}e %{SERVER_PROTOCOL}e %s", "httpRequest": {"requestMethod": "%m", "requestUrl": "%{REQUEST_URI}e", "status": "%s", "responseSize": "%l", "userAgent": "%{HTTP_USER_AGENT}e", "remoteIp": "%R:%{REMOTE_PORT}e", "serverIp": "%{SERVER_ADDR}e:%{SERVER_PORT}e", "referer": "%{SCRIPT_NAME}e", "latency": "%ds", "protocol": "%{SERVER_PROTOCOL}e"}}'

clear_env = no

; Ensure worker stdout and stderr are sent to the main error log.
catch_workers_output = yes
decorate_workers_output = no

; The issue that php-fpm starting and finish logs (e.g. "NOTICE: ready to handle connections") are still handled as errors (even if they are not). This is somehting I was not able to fix.
