[global]
error_log = /proc/self/fd/2

; https://github.com/docker-library/php/pull/725#issuecomment-443540114
log_limit = 8192

[www]
; php-fpm closes STDOUT on startup, so sending logs to /proc/self/fd/1 does not work.
; https://bugs.php.net/bug.php?id=73886
; Temp disabled because of php-fpm-healthcheck.sh logging lots of records
; access.log = /proc/self/fd/2
access.format='{"requestMethod":"%m","requestUrl":"%{REQUEST_URI}e","requestSize":"-","status":"%s","responseSize":"%l","responseSize2":"%{CONTENT_LENGTH}e","userAgent":"%{HTTP_USER_AGENT}e","remoteIp":"%R:%{REMOTE_PORT}e","serverIp":"%{SERVER_ADDR}e:%{SERVER_PORT}e","referer":"%{HTTP_REFERER}e","latency":"%ds","cacheLookup":"boolean","cacheHit":"boolean","cacheValidatedWithOriginServer":"boolean","cacheFillBytes":"string","protocol":"%{SERVER_PROTOCOL}e","severity":"%s","message":"%R %m %{REQUEST_URI}e %{SERVER_PROTOCOL}e %s"}'

clear_env = no

; Ensure worker stdout and stderr are sent to the main error log.
catch_workers_output = yes
decorate_workers_output = no

; The issue that php-fpm starting and finish logs (e.g. "NOTICE: ready to handle connections") are still handled as errors (even if they are not). This is somehting I was not able to fix.
